### ISSUE TITLE
[Feature]: Add a CodeQL Github Workflow

### ISSUE THREAD

**Issue by carlspring** [SAP/neonbee#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### The Problem

We should enable Github Advanced Security and enable the Vert.X support for CodeQL via the [carlspring/vertx-codeql-queries](https://github.com/carlspring/vertx-codeql-queries) custom query pack in a new Github Workflow.

### Desired Solution

Use the Vert.X support for CodeQL via the [carlspring/vertx-codeql-queries](https://github.com/carlspring/vertx-codeql-queries) custom query pack in a new Github Workflow.

### Resources

* [carlspring/vertx-codeql-queries](https://github.com/carlspring/vertx-codeql-queries)
* [carlspring/vertx-codeql-vulns](https://github.com/carlspring/vertx-codeql-vulns)

### Task List

The following tasks will need to be carried out:
* [x] Get admin access to the repository.
* [x] Enable GHAS.
* [x] Add a Github workflow for CodeQL.
* [ ] Test.

### Task Relationships

This task is:
* Related to:
  * carlspring/vertx-codeql-queries#1
  * carlspring/vertx-codeql-queries#10
